# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'corbalar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowC(object):
    def setupUi(self, MainWindowC):
        MainWindowC.setObjectName("MainWindowC")
        MainWindowC.resize(514, 804)
        MainWindowC.setStyleSheet("#centralwidget{\n"
"border-image: url(:/men/Menu-PNG-File.png);}")
        self.centralwidget = QtWidgets.QWidget(MainWindowC)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_TARHANA = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_TARHANA.setGeometry(QtCore.QRect(200, 270, 141, 51))
        self.pushButton_TARHANA.setObjectName("pushButton_TARHANA")
        self.pushButton_MERCIMEK = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_MERCIMEK.setGeometry(QtCore.QRect(200, 330, 141, 51))
        self.pushButton_MERCIMEK.setObjectName("pushButton_MERCIMEK")
        self.pushButton_DOMATES = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_DOMATES.setGeometry(QtCore.QRect(200, 390, 141, 51))
        self.pushButton_DOMATES.setObjectName("pushButton_DOMATES")
        self.pushButton_YAYLA = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_YAYLA.setGeometry(QtCore.QRect(200, 450, 141, 51))
        self.pushButton_YAYLA.setObjectName("pushButton_YAYLA")
        self.pushButton_EZOGELIN = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_EZOGELIN.setGeometry(QtCore.QRect(200, 510, 141, 51))
        self.pushButton_EZOGELIN.setObjectName("pushButton_EZOGELIN")
        self.pushButton_MANTAR = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_MANTAR.setGeometry(QtCore.QRect(200, 570, 141, 51))
        self.pushButton_MANTAR.setObjectName("pushButton_MANTAR")
        self.pushButton_SEBZE = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_SEBZE.setGeometry(QtCore.QRect(200, 630, 141, 51))
        self.pushButton_SEBZE.setObjectName("pushButton_SEBZE")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 280, 55, 16))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 340, 55, 16))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(350, 400, 55, 16))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(350, 460, 55, 16))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(350, 520, 55, 16))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(350, 580, 55, 16))
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(350, 640, 55, 16))
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        MainWindowC.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowC)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 514, 26))
        self.menubar.setObjectName("menubar")
        MainWindowC.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindowC)
        self.statusbar.setObjectName("statusbar")
        MainWindowC.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowC)
        QtCore.QMetaObject.connectSlotsByName(MainWindowC)

    def retranslateUi(self, MainWindowC):
        _translate = QtCore.QCoreApplication.translate
        MainWindowC.setWindowTitle(_translate("MainWindowC", "MainWindow"))
        self.pushButton_TARHANA.setText(_translate("MainWindowC", "TARHANA ÇORBASI"))
        self.pushButton_MERCIMEK.setText(_translate("MainWindowC", "MERCİMEK ÇORBASI"))
        self.pushButton_DOMATES.setText(_translate("MainWindowC", "DOMATES ÇORBASI"))
        self.pushButton_YAYLA.setText(_translate("MainWindowC", "YAYLA ÇORBASI"))
        self.pushButton_EZOGELIN.setText(_translate("MainWindowC", "EZOGELİN ÇORBASI"))
        self.pushButton_MANTAR.setText(_translate("MainWindowC", "MANTAR ÇORBASI"))
        self.pushButton_SEBZE.setText(_translate("MainWindowC", "SEBZE ÇORBASI"))
        self.label.setText(_translate("MainWindowC", "30 TL"))
        self.label_2.setText(_translate("MainWindowC", "30 TL"))
        self.label_3.setText(_translate("MainWindowC", "30 TL"))
        self.label_4.setText(_translate("MainWindowC", "35 TL"))
        self.label_5.setText(_translate("MainWindowC", "30 TL"))
        self.label_6.setText(_translate("MainWindowC", "40 TL"))
        self.label_7.setText(_translate("MainWindowC", "30 TL"))
import sembol_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindowC = QtWidgets.QMainWindow()
    ui = Ui_MainWindowC()
    ui.setupUi(MainWindowC)
    MainWindowC.show()
    sys.exit(app.exec_())
