# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'giris.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(623, 824)
        MainWindow.setStyleSheet("#centralwidget{\n"
"border-image: url(:/men/Menu-PNG-File.png);}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_CORBA = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_CORBA.setGeometry(QtCore.QRect(90, 300, 161, 61))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/cor/recipesoupicon_109875.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_CORBA.setIcon(icon)
        self.pushButton_CORBA.setObjectName("pushButton_CORBA")
        self.pushButton_EV = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_EV.setGeometry(QtCore.QRect(90, 390, 161, 61))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/evy/Dish_Pasta_Spaghetti_26373.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_EV.setIcon(icon1)
        self.pushButton_EV.setObjectName("pushButton_EV")
        self.pushButton_PIZZA = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_PIZZA.setGeometry(QtCore.QRect(90, 480, 161, 61))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/piz/pizza_food_fast_food_italian_food_icon_208020.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_PIZZA.setIcon(icon2)
        self.pushButton_PIZZA.setObjectName("pushButton_PIZZA")
        self.pushButton_HAMBURGER = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_HAMBURGER.setGeometry(QtCore.QRect(90, 570, 161, 61))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ham/32382hamburger_98925.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_HAMBURGER.setIcon(icon3)
        self.pushButton_HAMBURGER.setObjectName("pushButton_HAMBURGER")
        self.pushButton_TATLILAR = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_TATLILAR.setGeometry(QtCore.QRect(360, 350, 161, 61))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/tat/recipedessertcakeicon_109876.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_TATLILAR.setIcon(icon4)
        self.pushButton_TATLILAR.setObjectName("pushButton_TATLILAR")
        self.pushButton_ICECEKLER = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ICECEKLER.setGeometry(QtCore.QRect(360, 440, 161, 61))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/ic/Sex_on_the_Beach_25441.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ICECEKLER.setIcon(icon5)
        self.pushButton_ICECEKLER.setObjectName("pushButton_ICECEKLER")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 623, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_CORBA.setText(_translate("MainWindow", "ÇORBALAR"))
        self.pushButton_EV.setText(_translate("MainWindow", "EV YEMEKLERİ"))
        self.pushButton_PIZZA.setText(_translate("MainWindow", "PİZZA"))
        self.pushButton_HAMBURGER.setText(_translate("MainWindow", "HAMBURGER"))
        self.pushButton_TATLILAR.setText(_translate("MainWindow", "TATLILAR"))
        self.pushButton_ICECEKLER.setText(_translate("MainWindow", "İÇECEKLER"))
import sembol_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
