# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hamburger.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(515, 800)
        MainWindow.setStyleSheet("#centralwidget{\n"
"border-image: url(:/men/Menu-PNG-File.png);}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 260, 251, 16))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.pushButton_TAVUK = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_TAVUK.setGeometry(QtCore.QRect(200, 330, 93, 61))
        self.pushButton_TAVUK.setObjectName("pushButton_TAVUK")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 350, 121, 16))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.pushButton_ET = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ET.setGeometry(QtCore.QRect(200, 440, 93, 61))
        self.pushButton_ET.setObjectName("pushButton_ET")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(300, 460, 121, 16))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 515, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "*Hamburger içerisindeki ürünler aynıdır"))
        self.pushButton_TAVUK.setText(_translate("MainWindow", "Tavuk"))
        self.label_2.setText(_translate("MainWindow", "(105 TL)"))
        self.pushButton_ET.setText(_translate("MainWindow", "Et"))
        self.label_3.setText(_translate("MainWindow", "(150 TL)"))
import sembol_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
