# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'icecek.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(543, 802)
        MainWindow.setStyleSheet("#centralwidget{\n"
"border-image: url(:/men/Menu-PNG-File.png);}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_SU = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_SU.setGeometry(QtCore.QRect(210, 290, 111, 51))
        self.pushButton_SU.setObjectName("pushButton_SU")
        self.pushButton_CAY = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_CAY.setGeometry(QtCore.QRect(210, 370, 111, 51))
        self.pushButton_CAY.setObjectName("pushButton_CAY")
        self.pushButton_KOLA = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_KOLA.setGeometry(QtCore.QRect(210, 450, 111, 51))
        self.pushButton_KOLA.setObjectName("pushButton_KOLA")
        self.pushButton_LIMONATA = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_LIMONATA.setGeometry(QtCore.QRect(210, 520, 111, 51))
        self.pushButton_LIMONATA.setObjectName("pushButton_LIMONATA")
        self.pushButton_ICETEA = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ICETEA.setGeometry(QtCore.QRect(210, 600, 111, 51))
        self.pushButton_ICETEA.setObjectName("pushButton_ICETEA")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 310, 55, 16))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 390, 55, 16))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_KOLA = QtWidgets.QLabel(self.centralwidget)
        self.label_KOLA.setGeometry(QtCore.QRect(330, 460, 55, 16))
        self.label_KOLA.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_KOLA.setObjectName("label_KOLA")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(330, 530, 55, 16))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(330, 610, 55, 16))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 543, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_SU.setText(_translate("MainWindow", "SU"))
        self.pushButton_CAY.setText(_translate("MainWindow", "ÇAY"))
        self.pushButton_KOLA.setText(_translate("MainWindow", "KOLA"))
        self.pushButton_LIMONATA.setText(_translate("MainWindow", "LİMONATA"))
        self.pushButton_ICETEA.setText(_translate("MainWindow", "ICE-TEA"))
        self.label.setText(_translate("MainWindow", "( 10 TL)"))
        self.label_2.setText(_translate("MainWindow", "( 15 TL)"))
        self.label_KOLA.setText(_translate("MainWindow", "( 20 TL)"))
        self.label_4.setText(_translate("MainWindow", "(45 TL)"))
        self.label_5.setText(_translate("MainWindow", "( 35 TL)"))
import sembol_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
