# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tatli.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(534, 809)
        MainWindow.setStyleSheet("#centralwidget{\n"
"border-image: url(:/men/Menu-PNG-File.png);}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_KUNEFE = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_KUNEFE.setGeometry(QtCore.QRect(190, 300, 141, 51))
        self.pushButton_KUNEFE.setObjectName("pushButton_KUNEFE")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 320, 91, 16))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.pushButton_PASTA = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_PASTA.setGeometry(QtCore.QRect(190, 370, 141, 51))
        self.pushButton_PASTA.setObjectName("pushButton_PASTA")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 380, 55, 16))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.pushButton_WAFFLE = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_WAFFLE.setGeometry(QtCore.QRect(190, 440, 141, 51))
        self.pushButton_WAFFLE.setObjectName("pushButton_WAFFLE")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(340, 460, 71, 16))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.pushButton_SUFLE = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_SUFLE.setGeometry(QtCore.QRect(190, 510, 141, 51))
        self.pushButton_SUFLE.setObjectName("pushButton_SUFLE")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(340, 530, 55, 16))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.pushButton_KREHAVUC = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_KREHAVUC.setGeometry(QtCore.QRect(190, 590, 141, 51))
        self.pushButton_KREHAVUC.setObjectName("pushButton_KREHAVUC")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(340, 610, 55, 16))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 534, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_KUNEFE.setText(_translate("MainWindow", "KÜNEFE"))
        self.label.setText(_translate("MainWindow", "(50 TL)"))
        self.pushButton_PASTA.setText(_translate("MainWindow", "PASTA"))
        self.label_2.setText(_translate("MainWindow", "(60 TL)"))
        self.pushButton_WAFFLE.setText(_translate("MainWindow", "WAFFLE"))
        self.label_3.setText(_translate("MainWindow", "(70 TL)"))
        self.pushButton_SUFLE.setText(_translate("MainWindow", "SUFLE"))
        self.label_4.setText(_translate("MainWindow", "(60 TL)"))
        self.pushButton_KREHAVUC.setText(_translate("MainWindow", "KREMALI HAVUÇLU KEK"))
        self.label_5.setText(_translate("MainWindow", "(45 TL)"))
import sembol_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
